### ISSUE TITLE
Suppressed captchas

### ISSUE THREAD

**Issue by emmett97** [noahcoolboy/roblox-funcaptcha#10]
Hi, Noah, great project I'm sure you're aware you can manually get some suppressed funcaptchas mainly for signup but this lib can get at best 1 wave. Do you know the reason the lib can't get any suppressed mode captchas? Do you know the actual underlying cause?

**Comment by noahcoolboy** [comment]
Hi!
I have seen suppressed captchas before, but, I don't know what piece of information tells me it's suppresable.
It seems like Arkose Labs returns normal game info even if you can suppress it.
I would need to get one of those captchas again to see if there's anything different to a normal one which could tell me it's skippable

**Comment by emmett97** [comment]
I can surely provide information I know what pieces of the token differentiates it as well as some other knowledge do you have a means of private contact?

I'm currently abusing suppressed mode fyi it's insane but with your lib could be better.

I got some info I can privately share. 

My most recent test:
4,000 captchas for signup only, all in suppressed mode in a hour with extensive manual "involvement". Not automated

**Comment by noahcoolboy** [comment]
You can contact me on discord
noah#8315
I'm interested in adding support for suppresed captchas in the library

**Comment by doggo1000** [comment]
I believe you are talking about the "Pick any square" captcha which automatically gets marked as solved, however, you must have a perfect captcha score, have a residential IP and solve it 1 time every 10-100 tokens.
![image](https://user-images.githubusercontent.com/80135337/158038727-de2216be-2c71-4e3b-9347-a296618baffa.png)
