### ISSUE TITLE
callback for signingup/logging in

### ISSUE THREAD

**Issue by ghost** [noahcoolboy/roblox-funcaptcha#11]
I'm going to be honest, I have no knowledge of how to use this, but how could we use the callback.

**Comment by noahcoolboy** [comment]
Hi!
Documentation can be found in the readme
roblox-funcaptcha doesn't use callbacks, but uses JavaScript promises
If you want to use callbacks, you can use [node's callbackify function](https://nodejs.org/api/util.html#utilcallbackifyoriginal)

**Comment by ghost** [comment]
@noahcoolboy  I'm trying to convert  https://github.com/v3rz/Roblox-Account-Gen for my application, and instead use this for simplicity and maybe to test some AI in a simple way, and I'm not sure how I'd do it (I'm bad at javascript but this is probably one of the best libraries across languages)

**Comment by noahcoolboy** [comment]
I recommend [undici](https://www.npmjs.com/package/undici) for your HTTP Requesting needs
If you're up for it, you can try to recreate this library in python
Good luck!
