### ISSUE TITLE
captchaID

### ISSUE THREAD

**Issue by ghost** [noahcoolboy/roblox-funcaptcha#12]
Whenever I get the correct captcha ID from the signup API, using roblox-thots' captcha code maker it doesn't work,

`

{"reasons":["Captcha"],"failureDetails":[{"code":2,"message":"Captcha Failed.","fieldData":"9iCJiwA98sFXEvfPxCMYWS,FtcadsDXal7KTGV9.8yEhAYqrdXogvVKeb8hWluBJsP9X/FyzkYfF82ZF6EAWrCF2CEeN0vKxfilMhAPGmcjrtpuxvC4mFP808a9cUaejHBLSM1lmbWhElvrBMKXVCnIiiltIdJnQFf5l8CfbEFq9oceTixoWsPNgi9BX7gGh6X7WGwxdYo3iwRHnW2C4W3acRsppNAvGKlwM3dwzalCxyHL+TSANTRqn9PBkXNxOQPaAcOJc0zJzmEcYR0OakK0DKk2b3TDv0UCpURmlbVpo5/Jd2NQ8S7b3sq0oCIY5WuVTiMsuhffNcU/3t8hKzzjkl4kuH4rY"}],"errors":[{"code":2,"message":"Captcha Failed.","fieldData":"9iCJiwA98sFXEvfPxCMYWS,FtcadsDXal7KTGV9.8yEhAYqrdXogvVKeb8hWluBJsP9X/FyzkYfF82ZF6EAWrCF2CEeN0vKxfilMhAPGmcjrtpuxvC4mFP808a9cUaejHBLSM1lmbWhElvrBMKXVCnIiiltIdJnQFf5l8CfbEFq9oceTixoWsPNgi9BX7gGh6X7WGwxdYo3iwRHnW2C4W3acRsppNAvGKlwM3dwzalCxyHL+TSANTRqn9PBkXNxOQPaAcOJc0zJzmEcYR0OakK0DKk2b3TDv0UCpURmlbVpo5/Jd2NQ8S7b3sq0oCIY5WuVTiMsuhffNcU/3t8hKzzjkl4kuH4rY"}]}
Failed to create
`
 so how do we get it using javascript?

**Comment by noahcoolboy** [comment]
What?
This is not an issue with my library
The captcha ID doesn't have to be given to my library but to the signup api after solving the captcha
You might be confusing it with the blob, which IS required, by passing it to the getToken function
