### ISSUE TITLE
Where is the inspiration from crypto.js

### ISSUE THREAD

**Issue by devlzcode** [noahcoolboy/roblox-funcaptcha#13]
how did u come the conclusion to make it the way it is?

**Comment by noahcoolboy** [comment]
Not sure what you mean by that?
Arkose Labs uses encryption when making api requests to their solving endpoint.
This is why the crypto module is needed.

**Comment by devlzcode** [comment]
> Not sure what you mean by that?
> 
> Arkose Labs uses encryption when making api requests to their solving endpoint.
> 
> This is why the crypto module is needed.

I mean more like is it a arkose labs specific encryption or does arkose labs allow any encryption as long as its aes cbc

**Comment by noahcoolboy** [comment]
I'm not sure if it is specific to arkose labs, but I haven't really seen it anywhere else
I made it by looking at the source code behind funcaptcha on the roblox website
Look for `ALFCCJS` in [funcaptcha_js](https://roblox-api.arkoselabs.com/cdn/fc/js/b3931db6b9ae5c838421b3ac1f7a72e891a04a56/standard/funcaptcha_api.js)

**Comment by devlzcode** [comment]
ah okay cause I was wondering if this salting method was crucial to the library working properly
```js
 for (let x = 0; x < 3; x++) {
            dx = md5.update(Buffer.concat([
                Buffer.from(dx),
                Buffer.from(key),
                Buffer.from(salt)
            ])).digest()

            salted += dx.toString("hex")
            md5 = crypto.createHash("md5")
        }
```

**Comment by noahcoolboy** [comment]
Yes, it is
Failing to encrypt with the proper key will give an impossible to solve captcha
