### ISSUE TITLE
Unable to correctly answer

### ISSUE THREAD

**Issue by abstracthaven** [noahcoolboy/roblox-funcaptcha#3]
No matter what number I enter I'll get the response 'not answered.' and yes, I'm following the image guide. (this was with example.js)

Also, I was unable to get the properties: Session.info, Session.challengeID

![Screenshot (34)](https://user-images.githubusercontent.com/39888213/145701532-f20cd012-c756-49ae-86ef-a50429cdf0d3.png)

**Comment by noahcoolboy** [comment]
You can see in the image that the last response was saying you were done with it, but didn't solve it correctly

The following is in the documentation:
A response of {"response": "not answered"} means you haven't finished the captcha yet. There are still more waves left.
A reponse of {"response": "answered", "solved": false, "incorrect_guess": "", "score": 3 } means you have finished the captcha, but failed it. You have answered incorrectly at least once.
A reponse of {"response": "answered", "solved": true, "incorrect_guess": "", "score": 3 } means you have successfully finished the captcha. You have answered correctly and are good to go.

**Comment by abstracthaven** [comment]
Yes, I understand that, but those were the responses I was getting when answering it how it should be. Could you test it yourself just to confirm it's not an issue with the library? I even generated 20 different captchas just answering '1' and not once did it say it was correct when that's statically improbable. I even tried different variations of your guide image and still couldn't correctly answer it.

**Comment by abstracthaven** [comment]
Heres both an example of the issue with the terminal response and generated image:

![Screenshot (35)](https://user-images.githubusercontent.com/39888213/145764377-18df5eb1-8174-48ab-8f87-b4f7e6cd1125.png)
![0](https://user-images.githubusercontent.com/39888213/145764389-b723345c-d2bc-43b0-b3f6-66ac31c541a3.gif)

**Comment by noahcoolboy** [comment]
I can assure you that your answer was infact sent to the captcha servers
The library simply returns the response of their API, which says it wasn't answered when you haven't finished the captcha (more waves to do)

**Comment by abstracthaven** [comment]
Thank you, I understand now. I wrongly assumed that the captcha would finish immediately when the first wave was answered correctly.
