### ISSUE TITLE
Amazing work- one tip for the documentation

### ISSUE THREAD

**Issue by foy-kinjo** [noahcoolboy/roblox-funcaptcha#6]
First off, incredible work here. Idk how you figured all this out but it must have taken forever. One thing I had to figure out was that the originalToken itself was not enough to send to the login API. It needs to be the full token contained in the promise from the getToken function (includes a bunch of metadata at the end). It might be helpful to note this in the documentation. One other question I had was, how does the BDA work since its not coming from a browser? Is it okay to just have the same one each time since it's coming from an API instead?

**Comment by noahcoolboy** [comment]
Thank you! Making this library did take some time, yes.

originalToken SHOULD be the only thing which needs to get sent, but using the token from getToken is preferred.

As for the BDA, the windowshash and protohash are randomized (as well as some other values).
The browser fingerprint doesn't get randomized, but it does not seem like it affects Arkose Labs.
Arkose Labs decides on the amount of waves you get by the IP it is coming from.
You can always randomize the browser fingerprint by adding some code which randomizes the fonts from the fingerprint.

**Comment by foy-kinjo** [comment]
Very helpful thanks. originalToken kept giving me token validation errors from Roblox, but I'm sure there are different cases. Thanks again!
