### ISSUE TITLE
Question on Method 1 support

### ISSUE THREAD

**Issue by foy-kinjo** [noahcoolboy/roblox-funcaptcha#7]
This question is in reference to: "The type of game. 1 is the ball you have to rotate (not supported)" and from my own testing. Was this problem just too hard/impossible to solve? or have you had a chance to look at it yet? 

After testing a bunch it seems that FC gives this to me as a 'harder' challenge and I'm wondering if there is a way to support this method or to prevent it from happening. One possible workaround seems to be just retrying until the tile method is returned, but of course that isn't optimal. Do you know anything about the expected answer format for rotation problems? Is the number of rotations possible variable? I'm assuming the answer is some form of number of rotations, but haven't been able to correctly answer it yet.

**Comment by noahcoolboy** [comment]
I had not implemented the ball game because it simply isn't used by roblox
As for the 'harder' captchas, I'm trying to figure out ways to not get detected
Arkose Labs has recently started taking libraries as such more seriously and have implemented better detection
I could take a look at supporting the ball captcha, but I simply think it isn't needed (since this library is designed for roblox anyway)

**Comment by foy-kinjo** [comment]
I've been getting method_1 rotation captcha's rather frequently after testing- with external Roblox login. Right now I'm getting about 50/50 tile game and rotation game after heavy testing. I think Roblox does start giving it after a while. It only seems to be when done externally though, I can't seem to get the Roblox website itself to give me a rotation game. Otherwise I'd start some network analysis on the answers

**Comment by noahcoolboy** [comment]
I have noticed that the ball game is returned when something is incorrect (often with the fingerprint)
I'm currently trying to find the source of the issue
If I don't manage to get it fixed, as a last resort, I'll implement support for ball captchas

**Comment by foy-kinjo** [comment]
Oh that could be the issue. I've noticed that answering all the way through doesn't work (which could indicate a previous failure). After a couple answers the library produces this stack trace:

`Attempting to get image..
(node:10704) UnhandledPromiseRejectionWarning: InvalidArgumentError: invalid url
    at .../node_modules/undici/index.js:56:13
    at .../node_modules/roblox-funcaptcha/lib/http.js:5:9
    at new Promise (<anonymous>)
    at CustomSession.http (.../node_modules/roblox-funcaptcha/lib/http.js:4:12)
    at .../node_modules/roblox-funcaptcha/lib/session.js:24:34
    at new Promise (<anonymous>)`
    
    Edit: after a couple answers to the ball game*

**Comment by noahcoolboy** [comment]
Hmm, you might have answered one time too much?
Looking at the stack trace, this seems to originate from the getImage function in session.js
There is an array of URLs of each wave image
My theory is that you were trying to request the next image while the captcha was already done
Since `this.imgs[this.wave]` most likely returned undefined (because the wave > waves)

**Comment by foy-kinjo** [comment]
My logic works for the tile game every time, only on the ball game does that happen. It might be too many answers, but I think thats because I specifically check for the "{"response": "answered", "solved": X, .." line. When done via the ball game, that never gets returned, only: {response: 'not answered'}. So for a 5 wave game I got that all 5 times including on the last try. But if your theory on the ball game only appearing when something is invalid is correct, it makes sense that I don't get a valid response back after the last answer

**Comment by noahcoolboy** [comment]
I have updated the fingerprint and library
Please run `npm i roblox-funcaptcha` to update
This should fix the ball game issue
If you still encounter issues, please do tell me
