### ISSUE TITLE
[FIXED] Roblox' Signup Public Key Causes Arkose Labs Timeout?

### ISSUE THREAD

**Issue by noahcoolboy** [noahcoolboy/roblox-funcaptcha#8]
While I don't think many people know about funcaptcha's internal workings, it's still worth the shot to ask
I have recently been experiencing issues trying to use roblox' signup public key
When putting every answer correctly, it will give a "{ response: 'timed_mode_timeout' }" error
This only happens when the answers are correct, not when one of them is incorrect
See screenshot below (This was solved at human speed, got the error multiple times)
![image](https://user-images.githubusercontent.com/46800081/154533085-bace51e2-1072-4df0-8c02-98eea71efa83.png)
If anyone knows how to remediate this issue, please tell me

**Comment by jluims** [comment]
Has this been fixed? I'm still getting timed_mode_timeout

**Comment by noahcoolboy** [comment]
> Has this been fixed? I'm still getting timed_mode_timeout

This library is no longer maintained

**Comment by jluims** [comment]
My bad
