### ISSUE TITLE
Getting ball game more frequently- trying to find solution

### ISSUE THREAD

**Issue by foy-kinjo** [noahcoolboy/roblox-funcaptcha#9]
Hi, so I have been getting the game ball frequently. If I try after waiting a while I will get the tile game, but if I try again soon after I am getting the ball game. I have discovered that Roblox/FC does actually serve this challenge (I set my VPN location to a different area  a couple of times). When I got the ball game I captured the encrypted answers being sent to Funcaptcha. I am now trying to decode them so I can work on a solution to the ball game. I'm wondering if you could explain how you figured how to properly encrypt and send the answers for the tile game. Here are example payloads for answering the ball game:

Round 1
Payload:

* 		session_token: 992620c6f2af15199.6479599201
* 		game_token: 796620c6f2c7be4b2.8078549001
* 		sid: us-east-1
* 		guess: {"ct":"CPp8mNQzYYzmQ7GRUurFoQ==","iv":"743424fdb49bdb6c287799781a04ecff","s":"3f571baa3513cb2d"}
* 		analytics_tier: 40
* 		bio: eyJtYmlvIjoiIiwidGJpbyI6IiIsImtiaW8iOiIifQ==

Round 2
Payload:
* 		session_token: 992620c6f2af15199.6479599201
* 		game_token: 796620c6f2c7be4b2.8078549001
* 		sid: us-east-1
* 		guess: {"ct":"geKEsbOTEANoEhDMbl1qdw==","iv":"4be33d490aff50a492c4548a15d432e3","s":"650909b65564be06"}
* 		analytics_tier: 40
* 		bio: eyJtYmlvIjoiIiwidGJpbyI6IiIsImtiaW8iOiIifQ==

Round 3
Payload:
Payload:
* 		session_token: 992620c6f2af15199.6479599201
* 		game_token: 796620c6f2c7be4b2.8078549001
* 		sid: us-east-1
* 		guess: {"ct":"zqamXCI78aIDpe8YxXYHdawRs8XQUs77L8hc15HR6Uo=","iv":"f8186b2edff34bc9e9572573d4aae50f","s":"a1633bee656a8b74"}
* 		analytics_tier: 40
* 		bio: eyJtYmlvIjoiIiwidGJpbyI6IiIsImtiaW8iOiIifQ==

If I can decrypt the answers being sent it will be a good step towards trying to figure out how to formulate them.

**Comment by noahcoolboy** [comment]
Hi!
I have decrypted your answers
Round 1: `-180.00`
Round 2: `-180.00,90.00`
Round 3: `-180.00,90.00,-135.00`
If you would like to implement support for the ball captcha, you are more than welcome!

**Comment by foy-kinjo** [comment]
Awesome thank you! If I have time I will definitely work on adding support here. Did you decrypt using the same functions that are currently in the lib (crypto.js)? I checked some online decrypters for AES256, but couldn't get the answers like above.

**Comment by noahcoolboy** [comment]
Yes, I did!
You can use the decrypt function from crypto.js
Data argument is encryption information of the JSON in string form, the key is the session_token
